### PR TITLE
Add contrib file, fix ioctl support and max page alloc decrement on d…

### PR DESCRIPTION
**Pull request by pkoutoupis**
…iscard, and add size shrink support

* Added CONTRIBUTING.md file
* Clean up ioctl support. Let kernel general ioctls take over where appropriate and add IOCTL_RD_BLKFLSBUF to truncate rd device appropriately.
* Fix bug and update (decrement) maximum page count on discard request.
* Add shrink rd volume support. It will not go below the maximum sector allocated.

### CODE REVIEW

**Comment by pkoutoupis** [comment]
@betawaffle In this branch, I added shrink support. Whenever you get the chance, check it out and let me know what you think/find.

**Comment by pkoutoupis** [comment]
Also, while discard can/will work, I fixed the BLKFLSBUF truncate/page invalidation by adding a new ioctl:
```
#define IOCTL_RD_BLKFLSBUF      0x0531
[ ... ]
rc = ioctl(fd, IOCTL_RD_BLKFLSBUF, 0);
```
A full example can be see in `test/rxflush.c`.

**Comment by pkoutoupis** [comment]
@betawaffle I do not know if you had a chance to check this out but if you did, any thoughts? I would really like to see if it affects performance for you because of an added semaphore to attempt not allocating additional pages while shrinking the block device (a potential race condition: shrinking while actively writing).

**Comment by betawaffle** [comment]
I haven't gotten a chance, but I doubt it would be problematic for performance. Even if it was, I think correctness is more important. That said, in our use case that either wouldn't happen, or would be considered user-error or misuse.

**Comment by pkoutoupis** [comment]
@betawaffle Good morning. Just seeing if you had the chance to check this one out. I primarily wanted to make sure that the performance was not affected by the changes.

**Comment by betawaffle** [comment]
> @betawaffle Good morning. Just seeing if you had the chance to check this one out. I primarily wanted to make sure that the performance was not affected by the changes. In my local testing, I did not see any difference.

Unfortunately I haven't, but like I said before, it's likely fine.

**Comment by pkoutoupis** [comment]
OK. I will run a few more tests (testing the changes) and merge the code. Thank you.

**Pull request merged**
