### PR TITLE
Removing deprecated REMAKE_INITRD option in dkms.conf.

### PR DESCRIPTION
**Pull request by pkoutoupis**
REMAKE_INITRD has been deprecated in dkms version 3.x and later.

### CODE REVIEW

**Review by matteotenca — APPROVED** [review]
Hello @pkoutoupis ,
I tested this configuration under four different Ubuntu distros, with no problem whatsoever.

**Comment by pkoutoupis** [comment]
Thanks @matteotenca!

**Comment by Augusto7743** [comment]
Tested in both Ubuntu 18 32 bits and 20.04.6 64 bits ... working ...
Thanks ...

**Comment by pkoutoupis** [comment]
Thank you @Augusto7743.

**Pull request merged**
