### PR TITLE
Really small changes to module/Makefile

### PR DESCRIPTION
**Pull request by Shub77**
Changed the if/else/endif syntax and made some error messages nicer

I changed the `1>&2 2>/dev/null` syntax cause not working well on Ubuntu.
Changed the if/else/endif chains to a cleaner syntax.
Switched to `echo $$?` to check the return code, it is simpler and works well.
I removed `"..."` and final `.` from error messages. The `.` is added by Make.

These changes should be tested on Centos though.

And are really small things!

Bye!

### CODE REVIEW

**Comment by pkoutoupis** [comment]
@Shub77: Did you also test this on CentOS (or RHEL)? I will review this shortly. Thank you!

**Comment by Shub77** [comment]
> 
> 
> @Shub77: Did you also test this on CentOS (or RHEL)? I will review this shortly. Thank you!

I did not. I'll try today, I have to install it on a VM. Thanks for your work!

**Comment by pkoutoupis** [comment]
I just finished testing it on CentOS. Looks good. Also checked it out on my local Ubuntu build. Just like your tests, that too looked good. Thank you for this.

**Comment by Shub77** [comment]
You're welcome!

**Pull request merged**
