### PR TITLE
Feature/module metrics tunings

### PR DESCRIPTION
**Pull request by pkoutoupis**
* Added memory usage in rapiddisk module.
* Added lock/unlock functionality to set RapidDisk volume to read-only and back.

### CODE REVIEW

**Comment by pkoutoupis** [comment]
@betawaffle
Usage is tracked by page allocation but represented in bytes:
```
$ cat /sys/kernel/rapiddisk/devices 
Device	Size	Errors	Used
rd0	262144	0	262144
rd1	134217728	0	2097152
```

Also, I did not have to implement a read-only function in the actual kernel module code. The `block_device` structure in the kernel (`linux/blk_types.h`) has a `bd_read_only` boolean variable that handles that via an `ioctl()`: `BLKROSET`. I show a good example of how to make use of this ioctl in this branch under `test/rxro.c`. It works the exact same way as using `blockdev --setro /dev/rd0` or `blockdev --setrw /dev/rd0`.

Anyway, I implemented lock (`-L`) and unlock (`-U`) functionality in the userspace utility to enable these lock/unlock functions over REST. You will see that code in here too.

Although, now that I think about it, it may be useful to make use of BLKROGET to provide lock status in a general listing of devices. I will add that example in the `test/rxro.c` by tomorrow. Look for another commit.

**Comment by betawaffle** [comment]
Awesome, thanks for this!

**Comment by pkoutoupis** [comment]
@betawaffle The timestamp in my VM is off and it shows that I pushed my commit prior to your comment but that is not the case. Anyway, I just pushed new code retrieving lock state via the `BLKROGET` ioctl (which again is the same as using `blockdev --getro /dev/rd0`).

**Comment by pkoutoupis** [comment]
@betawaffle Any thoughts on this branch? There is no real rush but I was hoping to merging it to master soon.

**Comment by betawaffle** [comment]
It looks good to me. I haven't had time to test it yet, but I assume it works as advertised.

**Comment by pkoutoupis** [comment]
@matteotenca Did you want to take a quick look before I merge this into master?

**Comment by matteotenca** [comment]
> @matteotenca Did you want to take a quick look before I merge this into master?

@pkoutoupis I am sorry, I can't look at this now! I am on vacation with nearly no internet access - and positive to Covid (feeling ok).

**Comment by pkoutoupis** [comment]
@matteotenca I am sorry to hear that (but am glad that you feel ok) and I hope you get better soon.

**Pull request merged**
